### ISSUE TITLE
[Enhancement] License

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#1]
Hello, @wert007,

Thank you for your project!  I would like to contribute but at the moment, I do not know which conditions I need to keep in mind therefore.

Would you please consider to add a license of your choice?  Licenses usually imply the basic circumstances how a contribution to a project can be made.

Furthermore, a license of your choice makes it easier for others to credit your work in their projects and helps you to save your rights and freedoms as the author.

In doubt, MIT or GPL 2.0 (or later) are usually a good choice.

**Comment by wert007** [comment]
Done, thanks for your interest 😄
