### ISSUE TITLE
[Question] "Multiple" or "Multiply"?

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#10]
Regarding the option documentation, I am unsure whether it should rather be "multiply" instead of "multiple".

After all, the word annotates the verb "specify", right?  From my point of view, this would actually require an adverb...  Did you already check it with `languagetool` or so?

If a change should be necessary, I would suggest to add it to #9.

**Comment by wert007** [comment]
multiple, since it reads more like "multiple values specified".

**Comment by kevinmatthes** [comment]
And did you `languagetool` it or something similar?

Furthermore, why do the descriptions use French Spacing although English in general does not?

**Comment by kevinmatthes** [comment]
Another point:  should not the option descriptions rather use Imperative / Present instead of Indicative / Simple Present, as Cargo does it, for example?

**Comment by kevinmatthes** [comment]
Regarding #7, I just added the description for `--help` to #9 since it already applies Imperative / Present.

**Comment by wert007** [comment]
> And did you `languagetool` it or something similar?

I asked @Ranplax
 
> Furthermore, why do the descriptions use French Spacing although English in general does not?

I'm not sure what you mean by French Spacing 😅

**Comment by wert007** [comment]
> Another point: should not the option descriptions rather use Imperative / Present instead of Indicative / Simple Present, as Cargo does it, for example?

I guess you are right. I just wrote them without overthinking them too much 😅

**Comment by kevinmatthes** [comment]
French Spacing is a LaTeX feature.  In languages like English or Italian, it is common to place two space characters after finishing a phrase (. ! ? : ‽ ...).  Languages like French or German just place one space character after a phrase was ended.  LaTeX's `babel` cares for the correct style, by default.

But when authoring software, software engineers need to care for this convention themselves since there is no LaTeX to fix it automatically (except for Doxygen but only in PDF mode).  This is why I would like to outline that we need to agree on how to handle French Spacing.

For instance, my fixes of the `usage` function ***do not*** use French Spacing (`Usage:  commit-analyzer`) which is correct in the terms of English typography but your option descriptions ***do*** use French Spacing which is often considered a mistake.  A common style for such things helps to keep the application's overall appearance tidy.

**Comment by wert007** [comment]
I see. And where exactly do we have French spacing?

**Comment by kevinmatthes** [comment]
Just like Cargo's `clippy` lints and fixes Rust code, there are also linters for natural languages.  `languagetool` is one of them.  It is a website where you enter the text to lint and it rates whether it is correct.  It supports many languages and even some common dialects of them.

Before ending up in a dispute about adverbs, such a natural language linter usually helps to solve such grammar issues since it is a neutral and objective instance.

**Comment by kevinmatthes** [comment]
> I see. And where exactly do we have French spacing?

In the option descriptions.  Always at the beginning of the second phrase, there is just one space character.

**Comment by wert007** [comment]
Hmm, I can not find examples, where this is used with full stops. Do you have maybe some?

**Comment by wert007** [comment]
Hmm, I can not find examples, where this is used with full stops. Do you have maybe some?

**Comment by kevinmatthes** [comment]
In my fork, the first occurrence of French Spacing is at line 15 of `src/main.rs`:

```
            "Filters after certain author names. ORs if multiple specified.",
```

But instead, it should rather be ***without French Spacing***:

```
            "Filters after certain author names.  ORs if multiple specified.",
```

Indeed, this is a very small detail.  But it is still part of the project.  And in my opinion, since we discussed whether or not to place syntactically possible but obsolete semicolons in #6, we should also care for this detail.

If you want to see the differences with and without French Spacing in action in a larger text, do the following:

* open one of your LaTeX projects in your LaTeX IDE
* add `\frenchspacing` right after `\begin{document}`, compile, and print one page of the resulting PDF
* change `\frenchspacing` to `\nonfrenchspacing`, recompile, and print the same page of the resulting PDF
* take a ruler and measure the distance between a full stop and succeeding lexeme on the same line of the same adjacent sentences

You will definitely encounter a difference.  This difference should be minded when writing text in a language which does not apply French Spacing.  And as I said, English is one these languages.  Proof:  set your `babel` of the concerning project to another language, and compare the differences of the results as described above, such as with `british` vs. `ngerman`, for instance.

**Comment by wert007** [comment]
But you are comparing here a mono spaced font with a variable spaced font. E.g. if I copy text from the English wikipedia
> Computer programming is the process of performing a particular [computation](https://en.wikipedia.org/wiki/Computation) (or more generally, accomplishing a specific [computing](https://en.wikipedia.org/wiki/Computing) result), usually by designing and building an [executable](https://en.wikipedia.org/wiki/Executable) [computer program](https://en.wikipedia.org/wiki/Computer_program). Programming involves tasks such as analysis, generating [algorithms](https://en.wikipedia.org/wiki/Algorithm), [profiling](https://en.wikipedia.org/wiki/Profiling_(computer_programming)) algorithms' accuracy and resource consumption, and the implementation of algorithms (usually in a chosen [programming language](https://en.wikipedia.org/wiki/Programming_language), commonly referred to as coding).

There is only one space after each full stop. However that space will be rendered does not matter too much imho.

**Comment by kevinmatthes** [comment]
On the other hand, avoiding of French Spacing is practiced in order to recognise the end of phrase more easily.  This also holds true for source code.

**Comment by wert007** [comment]
> On the other hand, avoiding of French Spacing is practiced in order to recognise the end of phrase more easily. This also holds true for source code.

Do you have any example of source code for that? Except of latex settings I do not really find anything for that..

**Comment by kevinmatthes** [comment]
* https://github.com/kevinmatthes/cffreference/blob/main/Main.hs
* https://github.com/kevinmatthes/cffreference/blob/main/LICENSE

The license header of the former does not apply French Spacing and my documentation strings neither.  To me, this looks more readable.  Just like the GPL 2.0 itself; see the latter link for an example.

**Comment by wert007** [comment]
I meant in other code bases. I expected you, to use the spacing style you're advocating for.. 😅

**Comment by kevinmatthes** [comment]
GNU Octave:  https://github.com/gnu-octave/octave

**Comment by kevinmatthes** [comment]
GCC:  https://github.com/gcc-mirror/gcc

**Comment by kevinmatthes** [comment]
The GNU Shell Intrinsics:  https://github.com/coreutils/coreutils

**Comment by wert007** [comment]
Thanks for your examples, but I have to admit, I'm not a fan of it.

But thanks anyway, I wasn't aware, this exists. But I think we should stick with singular spaces.

**Comment by kevinmatthes** [comment]
In summary:

* :wrench: change the mode and tense to Imperative / Present
* :wrench: revert French Spacing

By the way what did `languagetool` or any other English linter say to "ORs if multiple specified."?

**Comment by wert007** [comment]
Yes.

I didn't ask it. I'm open to other wordings in general though. But I'm pretty sure, that multiple is correct, since it is not referring to "specified".

**Comment by kevinmatthes** [comment]
And to which actually contained word it refers if not to specified?

**Comment by wert007** [comment]
> multiple, since it reads more like "multiple values specified".

An implied "values"

**Comment by kevinmatthes** [comment]
`languagetool` accepts both; how about just changing the wording to clarify?  To me, it still looks like "multiple" refers to "specified".

How about "ORs if specified multiple times"?

**Comment by wert007** [comment]
"ORs if specified multiple times" sounds good 👍

**Comment by kevinmatthes** [comment]
Fine!
