### ISSUE TITLE
[Question] Loc as the Difference Between Insertions and Deletions?

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#12]
Are you sure that the `loc` is calculated from the ***difference*** between the insertions and deletions?

Not only my version of Git considers the `loc` the ***sum*** of insertions and deletions, also GitHub does.  For instance, go to the [list of changed files from the latest Pull Request](https://github.com/wert007/commit-analyzer/pull/9/files) and hover the number on the left-hand side of `src/main.rs`.  (The README only had insertions, so that would be boring.)  GitHub shows to me then:  "45 changes: 24 additions & 21 deletions."

Did I misunderstand the purpose of the `Loc` struct or might that really be a candidate for a bugfix?

**Comment by wert007** [comment]
`Loc` stands for lines of code, so every commit can either increase or decrease the total number of lines of code.

The Loc struct was used to show the development of a software project over time. We choose the lines of code as a metric and used git to display them per day.

So no, this is not a bug.

**Comment by kevinmatthes** [comment]
Okay, thank you.

I am about to add some documentation to the code, I will add your explanation to the documentation.
