### ISSUE TITLE
[Feature Request] Make Quiet Behaviour Default

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#14]
How about making the monosyllabic behaviour the default and opting-in the verbose results by an appropriate option for debugging?

**Comment by kevinmatthes** [comment]
I suggested a possible implementation by #15.

Should it rather be the corresponding minuscule instead?  The verbosity levels like Git has them can be implemented analogously with both possibilities.

**Comment by wert007** [comment]
Wrote about that in the pull request. But I'm in favor of the feature as a whole.
