### ISSUE TITLE
[Bug] Crash Due to Missing LOC Diff

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#16]
It seems as if `commit-analyzer` tends to crash if no LOC diff is present in the input file.

Now, that the verbose output needs to be opted-in explicitly, I found out that line 121 always seems to cause a `CommitParseError::CommitMissing` when there is no LOC diff.

I did not trace down the bug completely, yet, but I assume that perhaps the LOC diff might be considered present, by default.

**Comment by wert007** [comment]
I'll look into it.

**Comment by kevinmatthes** [comment]
I already suggested a patch with sane further enhancements, see #17.
