### ISSUE TITLE
[Enhancement] CITATION.cff

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#2]
Hello, @wert007,

Thank you for your project!  I would like to cite your software in my papers but at the moment, I am unsure which metadata I should use therefore.

GitHub offers the feature to render BibTeX entries and APA citation texts from a configuration file named `CITATION.cff`.  It applies the community standard CFF, see https://github.com/citation-file-format/citation-file-format for details.  In brief, it is a YAML file in which you specify the data with which you want to be cited.  This can be either this repository itself or, in case that you already published an according paper about this project, for instance, another publication.

In order to ensure the correctness of your `CITATION.cff`, the CFF team provides a Python 3 CLI, see https://github.com/citation-file-format/cff-converter-python, and a GitHub Action, see both https://github.com/citation-file-format/cffconvert-github-action and https://github.com/kevinmatthes/blank/blob/main/.github/workflows/cffconvert.yml for the specification and a valid application of it, respectively.

With such a `CITATION.cff`, you can not only cite your own work in your papers but also create a list of further readings for people who are interested in your repository.  You just need to add their citation metadata in your `CITATION.cff`.  `cffreference`, see https://github.com/kevinmatthes/cffreference, helps you to do so.

I would like to ask you to consider to add an according `CITATION.cff` to your project in order to make a great project even better.

**Comment by wert007** [comment]
Hey @kevinmatthes,

feel free to cite, or not cite, this software in whatever way you like. Since this has only been a small personal project, I don't really care too much. 😅
