### ISSUE TITLE
[Enhancement] [Question] inline Attribute for Very Short Functions?

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#22]
Rust also offers the possibility to tag functions with only very few statements `inline`, just as C does.  Here is an example from the `sysexits` crate:  https://github.com/sorairolake/sysexits-rs/commit/493aa8807401cfcc0206c920d4287e08e04c17e1

Would this enhance `commit-analyzer`?

**Comment by wert007** [comment]
If you check the symbols of you release build, you will see, that rust (or more precisely llvm) already inlined most of the functions. So I do not think this would add anything, since it is already inlined automatically, where it makes sense.

**Comment by kevinmatthes** [comment]
Okay, this answers the question.
