### ISSUE TITLE
[Enhancement] Add Installation Manual to README

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#23]
There is a very simple way to install a working release binary of the application on one's machine using Cargo.

Shall I add a corresponding information to the README?

**Comment by wert007** [comment]
Hmm, I'm actually not aware of that, how does that work?

**Comment by kevinmatthes** [comment]
With Cargo, you are allowed install Rust crates with binary targets locally on your machine, typically in `~/.cargo/bin/`.  For instance, you can create an offline HTML version of the latest Rust book with the crate `mdbook`.  You install this crate with the following command:

```
cargo install mdbook
```

See for https://github.com/rust-lang/book for details.

This not only works with crates on crates.io but also with public Git projects and even local projects.  To install the latest stable version of `commit-analyzer`, just run:

```
cargo install --git https://github.com/wert007/commit-analyzer
```

However, installation is one thing, updating another one.  Since `mdbook` has versions but `commit-analyzer` does not, updating the latter one becomes slightly more difficult.  Updating a crate with versions just requires you to install it again using the same command as you used to install it.  Cargo will reject to update if you would download the same version again.  But for projects without versions, just as `commit-analyzer`, you need to overwrite the current version.  You can literally en`force` that:

```
cargo install --force --git https://github.com/wert007/commit-analyzer
```

I would like to suggest to add these information to the README since it adds more comfort to use the application and to outline the required additional "effort" to update the installed version.  This might help other people to install and experience the application themselves.

There are projects which have the same installation procedure, such as https://github.com/curlpipe/ox, a terminal text editor.

**Comment by kevinmatthes** [comment]
Basically, this implies a relationship of this issue to #13.

**Comment by wert007** [comment]
Yeah, that sounds good. 👍
