### ISSUE TITLE
[Question] Update Cargo Dependencies?

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#25]
Since there had been an update to `sysexits` in the last days, I wondered whether it would be a meaningful enhancement to update all dependency crates to their latest versions.

**Comment by wert007** [comment]
Since there are not really any changes in that update, and it is only a kind of "patch" update, this is not really necessary. 😅

**Comment by kevinmatthes** [comment]
It was a more general question with `sysexits` as an example.  To preview the crates which have been updated, just delete the `Cargo.lock` and run `cargo b` once.  This will recreate the file and automatically update the changed crates.  To fetch their names comfortably, run `git diff -U1 | grep name`.  On my machine, this gives:

```
 name = "autocfg"
 name = "libc"
 name = "num-integer"
 name = "num-traits"
 name = "sysexits"
```

There is also a GitHub feature named "Dependabot" which would automatically update the crates when required.  How about this?  It would correlate with #8.

**Comment by wert007** [comment]
Since I just removed `getopts` as dependency in a pull request, I think most of these should be resolved anyway.

**Comment by kevinmatthes** [comment]
In fact, just two updates could be omitted by doing so.  `num-integer`, `num-traits` and especially `sysexits` still need to be updated.  The first two crates originate from `chrono`; `sysexits` is quite likely to receive an important feature update within the next two weeks, I suppose.

The feature update brings the `Display` trait implementation in order to format the exit codes to strings which will definitely benefit the error handling, not only for debugging.  We could add the information with which exit code the application aborts to the error messages, for example.

**Comment by wert007** [comment]
Hmm, I think status codes are not too helpful to end users. If they are interested in them, they have a terminal, which will show that code to them. Otherwise the program should just use clear language to describe what exactly went wrong.
