### ISSUE TITLE
[Enhancement] Build Routine

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#4]
Hello, @wert007,

Thank you for your project!  I would like to build it but at the moment, I am unsure whether there might be special compiler flags and additional dependencies, i. e. software requirements in addition to those implicitly specified by your `Cargo.lock`, to mind.

I would like to ask you to consider to add a build script, such as a Makefile or a GNU Octave script with the same purpose, in order to communicate the build settings to mind to create a compilation of your software as it should be.

**Comment by wert007** [comment]
Hey @kevinmatthes,

you can just run it with `cargo run` (or `cargo run --release` for a version without debug symbols) or build it with `cargo build` (also supports the `--release` flag) which will build the project into the `target` directory.

That should be easy enough to not warrant a build script 😅
