### ISSUE TITLE
[Enhancement] Option Overview in README

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#7]
> This issue originates from #6 and was created in order to mark it as an open task.

The application documentation could be enhanced by adding an overview about the configured options to the repository README.

**Comment by kevinmatthes** [comment]
The minimal approach would be to just paste the output of `commit-analyzer --help` to the README.  What do you think about that, @wert007?

**Comment by wert007** [comment]
> The minimal approach would be to just paste the output of `commit-analyzer --help` to the README. What do you think about that, @wert007?

That's exactly how I would do it 👍

**Comment by kevinmatthes** [comment]
I will add it to #9.

**Comment by kevinmatthes** [comment]
But before, we should rather finish the discussion of #10.

**Comment by kevinmatthes** [comment]
:wrench: :heavy_check_mark:
